### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Narulacodes** [ktrvs/chatterbots#2]
Hi There,

Can i help you? if not, I  am working on a company now called NIC, no internet connection, ans wanted to make a discord bot, would you help please? Thanks.

**Comment by ktrvs** [comment]
I did spend a lot of time on this, and plan to build on it a lot more, so I'd rather keep it as mine for now. However, you are welcome to request new features and/or submit Pull Requests.

If you're interested in creating your own bot, I reccomend you look at [this](https://anidiotsguide_old.gitbooks.io/discord-js-bot-guide/content/getting-started/the-long-version.html). Chatterbots is also is MIT Licensed, so you can fork it and use the existing code towards your own.

Good luck! 😄 🎉

**Comment by Narulacodes** [comment]
Thank You!
